### ISSUE TITLE
Dead modal links on the site

### ISSUE THREAD

**Issue by wilhelmpaulm** [tjmonsi/uxphconf2017#1]
- [ ] page not found on links on the main page for https://www.uxphilippines.com/ when clicking on speakers.
- [ ] site height gets cut on the bottom part for large viewports
- [ ] does not scale completely for higher resolutions
- [ ] please pick a pledge opens a modal with content already available on the bottom part
- [ ] 'support' button should only be seen when in mobile view to limit scrolling
- [ ] it's not clear on the front page that the venue is TBA, you need to click on 'support' -> 'get a ticket' or 'get a ticket' first before finding out

**Comment by tjmonsi** [comment]
Hi @wilhelmpaulm  Thanks for sending us these. Would like to know what browser are you using and what version?

**Comment by tjmonsi** [comment]
Hi @wilhelmpaulm would it be ok to give us screenshots for points 2 and 3? I don't quite get what you mean.

numbers 4 - 6. Thanks for the suggestion and will look into it with the team. :)
