### ISSUE TITLE
About UXPH Section: What is the Section really about: the organization or the conference?

### ISSUE THREAD

**Issue by AshleyUy** [tjmonsi/uxphconf2017#3]
Sorry for being nitpicky but can this section be separated into two? The first paragraph talks about the conference itself tapos the header is "About UXPH" so which is this section about: UXPH as an org or the UXPH Conference? It also looks busy with clumps of text together compared to the minimalist theme from other sections.

![image](https://cloud.githubusercontent.com/assets/7195650/24318941/ea2ab560-1149-11e7-9c55-cca3d0bdd8be.png)

**Comment by jozzua** [comment]
Yeah we can have sub-titles above each paragraph.  To follow.

**Comment by jozzua** [comment]
Fixed with. https://github.com/tjmonsi/uxphconf2017/commit/78ffb9241610f7d89d36938e2c53ce32b4fa0042
