### ISSUE TITLE
When expanding question in FAQ, page jumps to anchor in Gallery

### ISSUE THREAD

**Issue by AshleyUy** [tjmonsi/uxphconf2017#4]
When you click the arrow button to expand a question in the FAQ section, the page jumps to the anchor in the Gallery section.

**Comment by jozzua** [comment]
Ashley I can't replicate this. Can you put steps to replicate and what's your current OS and browser?

**Comment by jozzua** [comment]
Also, wha typos were you referring to?

**Comment by tjmonsi** [comment]
I'll check this out
